n = input('Insert anything ')
print('The type refer n is',type(n))
print('Is alpha numeric?',n.isalnum())
print('Is alpha?',n.isalpha())
print('Is decimal?',n.isdecimal())
print('Is ASCII?',n.isascii())
print('Is string have space?',n.isspace())
print('Is lower?',n.islower())
print('Is upper case?',n.isupper())
print('Is printable?',n.isprintable())
print('Is N capitalized?',n.istitle())
